<?php

/**
 * This is the model base class for the table "{{car_brand}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CarBrand".
 *
 * Columns in table "{{car_brand}}" available as properties of the model,
 * followed by relations of table "{{car_brand}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 *
 * @property mixed $tblServices
 */
abstract class BaseCarBrand extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{car_brand}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CarBrand|CarBrands', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title', 'required'),
			array('title', 'length', 'max'=>200),
			array('id, title', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tblServices' => array(self::MANY_MANY, 'Service', '{{car_brand_to_service}}(car_brand_id, service_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'tblServices' => 'CarBrandToService',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'tblServices' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}