<?php

/**
 * This is the model base class for the table "{{car_model}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CarModel".
 *
 * Columns in table "{{car_model}}" available as properties of the model,
 * followed by relations of table "{{car_model}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $car_brand_id
 * @property string $title
 *
 * @property CarBrand $carBrand
 */
abstract class BaseCarModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{car_model}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CarModel|CarModels', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title', 'required'),
			array('car_brand_id', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>200),
			array('car_brand_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, car_brand_id, title', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'carBrand' => array(self::BELONGS_TO, 'CarBrand', 'car_brand_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'car_brand_id' => null,
			'title' => Yii::t('app', 'Title'),
			'carBrand' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('car_brand_id', $this->car_brand_id);
		$criteria->compare('title', $this->title, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}