<?php

/**
 * This is the model base class for the table "{{negotiation}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Negotiation".
 *
 * Columns in table "{{negotiation}}" available as properties of the model,
 * followed by relations of table "{{negotiation}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $hash
 * @property integer $service_id
 * @property integer $appliance_id
 * @property string $manager_name
 * @property integer $price
 * @property string $status
 * @property string $comment
 *
 * @property Appliance $appliance
 * @property Service $service
 */
abstract class BaseNegotiation extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{negotiation}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Negotiation|Negotiations', $n);
	}

	public static function representingColumn() {
		return 'hash';
	}

	public function rules() {
		return array(
			array('service_id, appliance_id, price', 'numerical', 'integerOnly'=>true),
			array('hash', 'length', 'max'=>64),
			array('manager_name', 'length', 'max'=>200),
			array('status, comment', 'safe'),
			array('hash, service_id, appliance_id, manager_name, price, status, comment', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, hash, service_id, appliance_id, manager_name, price, status, comment', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'appliance' => array(self::BELONGS_TO, 'Appliance', 'appliance_id'),
			'service' => array(self::BELONGS_TO, 'Service', 'service_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'hash' => Yii::t('app', 'Hash'),
			'service_id' => null,
			'appliance_id' => null,
			'manager_name' => Yii::t('app', 'Manager Name'),
			'price' => Yii::t('app', 'Price'),
			'status' => Yii::t('app', 'Status'),
			'comment' => Yii::t('app', 'Comment'),
			'appliance' => null,
			'service' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('hash', $this->hash, true);
		$criteria->compare('service_id', $this->service_id);
		$criteria->compare('appliance_id', $this->appliance_id);
		$criteria->compare('manager_name', $this->manager_name, true);
		$criteria->compare('price', $this->price);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('comment', $this->comment, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}